title: heysimone.exposed
description: WHAT IS SHE DOING??
twitter_username: heysimone
lang: en-US
copyright: "heysimone.exposed"
remote_theme: "mmistakes/jekyll-theme-basically-basic"
repository: heysimone/heysimone.github.io

plugins:
 - jekyll-remote-theme