title: heysimone.exposed
description: WHAT IS SHE DOING??
url: https://heysimone.exposed
twitter_username: heysimone
lang: en-US
remote_theme: "mmistakes/jekyll-theme-basically-basic"
repository: heysimone/heysimone.github.io

plugins:
 - jekyll-remote-theme